# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

# Creating Array

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
type(my_list)

list

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(3.0)

array([0., 1., 2.])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20,10)

array([], dtype=int32)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
np.arange(30,20)

array([], dtype=int32)

In [18]:
b=np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [19]:
np.arange(10,10)

array([], dtype=int32)

In [20]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [21]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [23]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [24]:
b1=np.zeros(2)#parameter tunning
b1

array([0., 0.])

In [25]:
np.zeros(5,dtype=int)#hyperparameter tunning

array([0, 0, 0, 0, 0])

In [26]:
zero=np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [32]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n=(5,7)
n1=(6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
n

(5, 7)

In [38]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [41]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [44]:
np.arange(3)

array([0, 1, 2])

In [46]:
from numpy import *

In [47]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
range(12)

range(0, 12)

In [49]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [50]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [51]:
np.random.rand(4)

array([0.07769696, 0.65697634, 0.53042755, 0.7718128 ])

In [52]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [53]:
np.random.rand(2,4)

array([[0.01323884, 0.29452573, 0.843164  , 0.04573125],
       [0.4457148 , 0.74476289, 0.11557048, 0.25344299]])

In [54]:
np.random.randint(2,20)

10

In [55]:
np.random.randint(0,2)

0

In [56]:
np.random.randint(1,10,4)

array([7, 9, 5, 1])

In [57]:
np.random.randint(1,3,5)

array([2, 2, 1, 2, 2])

In [58]:
np.random.randint(30,20,10)

ValueError: low >= high

In [59]:
np.random.randint(1)

0

In [61]:
np.random.randint(5,9)

7

In [62]:
np.random.randint(10,21,3)

array([10, 17, 17])

In [63]:
np.random.randint(1,12,10)

array([11,  9,  3, 11,  8,  9,  2,  5,  4,  4])

In [64]:
np.random.randint(10,40,(10,10))

array([[12, 31, 26, 20, 10, 26, 11, 23, 28, 18],
       [12, 26, 24, 29, 16, 22, 29, 16, 14, 31],
       [20, 38, 31, 16, 29, 38, 28, 19, 34, 31],
       [16, 20, 12, 39, 34, 27, 13, 14, 30, 15],
       [15, 31, 15, 12, 19, 17, 26, 37, 36, 27],
       [18, 15, 25, 25, 31, 12, 29, 38, 20, 26],
       [19, 25, 33, 19, 20, 11, 29, 14, 18, 28],
       [31, 37, 12, 11, 18, 16, 33, 15, 20, 34],
       [16, 28, 35, 30, 12, 33, 32, 24, 20, 37],
       [27, 38, 11, 38, 12, 38, 34, 26, 27, 10]])

In [66]:
b=np.random.randint(10,20,(5,4))
b

array([[19, 10, 11, 18],
       [13, 12, 18, 10],
       [13, 16, 17, 17],
       [15, 19, 11, 15],
       [19, 18, 11, 13]])

In [67]:
b[:]

array([[19, 10, 11, 18],
       [13, 12, 18, 10],
       [13, 16, 17, 17],
       [15, 19, 11, 15],
       [19, 18, 11, 13]])

In [68]:
b[0:2]

array([[19, 10, 11, 18],
       [13, 12, 18, 10]])

In [69]:
b

array([[19, 10, 11, 18],
       [13, 12, 18, 10],
       [13, 16, 17, 17],
       [15, 19, 11, 15],
       [19, 18, 11, 13]])

In [70]:
b[0:-1]

array([[19, 10, 11, 18],
       [13, 12, 18, 10],
       [13, 16, 17, 17],
       [15, 19, 11, 15]])

In [71]:
b

array([[19, 10, 11, 18],
       [13, 12, 18, 10],
       [13, 16, 17, 17],
       [15, 19, 11, 15],
       [19, 18, 11, 13]])

In [72]:
b[0,2]

11

In [73]:
np.random.randint(10,20,(4,4))

array([[14, 19, 11, 13],
       [11, 10, 14, 13],
       [12, 12, 13, 19],
       [10, 16, 17, 10]])

# Operations

In [75]:
a=np.random.randint(10,20,5)
a

array([16, 18, 19, 10, 19])

In [76]:
arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr2=np.random.randint(0,100,(10,10))

In [79]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [81]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [82]:
arr[:4]

array([0, 1, 2, 3])

In [83]:
arr2[:]

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [84]:
arr2[0:5]

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11]])

In [85]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [86]:
arr2[1,5]

7

In [87]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [88]:
arr2[-5,5]

8

In [89]:
arr2[-5,-5]

8

In [90]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [91]:
arr2[-5,-5]

8

In [92]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [93]:
arr2[-1,-2]

46

In [94]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [95]:
arr2[::-1]

array([[44,  9, 62, 34, 33, 73, 22, 29, 46, 79],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [21, 68,  7,  3, 50, 24, 90, 25, 89, 29]])

In [96]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [97]:
arr2[::-2]

array([[44,  9, 62, 34, 33, 73, 22, 29, 46, 79],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38]])

In [98]:
arr2

array([[21, 68,  7,  3, 50, 24, 90, 25, 89, 29],
       [75,  9, 94,  3, 67,  7, 38, 27, 54, 38],
       [66, 48, 34,  6, 16, 32, 86, 34, 17, 15],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [24, 21, 61, 89, 89, 79, 93, 21, 56, 11],
       [29, 83, 56, 73, 35,  8, 83, 31, 75, 62],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [94, 75, 69, 69, 71, 49, 22, 13, 54, 92],
       [ 6, 30,  9, 69,  2, 89, 50, 99, 37, 16],
       [44,  9, 62, 34, 33, 73, 22, 29, 46, 79]])

In [99]:
arr2[::-3]

array([[44,  9, 62, 34, 33, 73, 22, 29, 46, 79],
       [50, 23, 34, 35, 99, 43, 29, 95, 55, 60],
       [ 5, 87, 96, 21, 10,  3, 85, 26, 62, 10],
       [21, 68,  7,  3, 50, 24, 90, 25, 89, 29]])

In [100]:
arr

array([0, 1, 2, 3, 4, 5])

In [101]:
arr.max()

5

In [102]:
arr.min()

0

In [103]:
arr

array([0, 1, 2, 3, 4, 5])

In [104]:
arr.mean()

2.5

In [105]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [107]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

In [108]:
arr

array([0, 1, 2, 3, 4, 5])

In [111]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [112]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [113]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [114]:
arr

array([0, 1, 2, 3, 4, 5])

In [115]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [116]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [117]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [119]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [120]:
arr.reshape(3,2,order='K')

ValueError: order 'K' is not permitted for reshaping

In [121]:
arr

array([0, 1, 2, 3, 4, 5])

In [122]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [124]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [125]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [126]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [127]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [128]:
arr

array([0, 1, 2, 3, 4, 5])

In [129]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [130]:
mat=np.arange(0,100).reshape(10,10)

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
row=4
col=5

In [133]:
col

5

In [134]:
row

4

In [135]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
mat[row,col]

45

In [137]:
mat[4,5]

45

In [138]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
col=6

In [141]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# with slices

In [142]:

mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [143]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [145]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [147]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [148]:
row

4

In [149]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [150]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [151]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [152]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [154]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [155]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [156]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
row

4

In [158]:
col

6

In [159]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [160]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [161]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[1,4]

14

In [163]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [166]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [167]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [171]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [173]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [179]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [181]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [184]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [185]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [186]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [188]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[0,1]

1

In [190]:
mat[1,6]

16

In [191]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [193]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [194]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [196]:
mat[3,5]

35

In [197]:
mat[1:2,2:4]

array([[12, 13]])

In [198]:
mat[2:3,2:3]

array([[22]])

In [199]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [201]:
mat[2:3,4:5]

array([[24]])

# Masking

In [203]:
mat#we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
id(mat)

3173202222928

In [205]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [206]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [207]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [208]:
mat[mat==50]

array([50])

In [209]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [214]:
a3=mat[mat>=50]
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [215]:
a4=mat[mat==50]
a4

array([50])

In [216]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [217]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [218]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])